<h1>Model Making 


<h2>Libraries

In [12]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import os
import plotly.express as px


### Reading all the files and concatinating them 

In [13]:
# reading all the files

cwd = os.path.abspath('dataset2')
file_list = os.listdir(cwd)
file_list

['altoFYP DataSet1-to10.csv',
 'BolanFYPDataset1to10.csv',
 'fortunerFYP DataSet1-to10.csv',
 'mark-xFYP DataSet1-to10.csv',
 'tucsonFYP DataSet1-to10.csv',
 'vitzFYP DataSet1-to10.csv',
 'withdatesalsvinFYP DataSet1-to10.csv',
 'withdatescityFYP DataSet1-to10.csv']

In [14]:
df_con = pd.concat([pd.read_csv('dataset2/'+f) for f in file_list], ignore_index= True)
df_con

Unnamed: 0                                      AD_Name    AD_id  \
0              0                   Suzuki Alto S Package 2020  8399373   
1              1                          Suzuki Alto VX 2021  8434278   
2              2                   Suzuki Alto VXR (CNG) 2011  8433614   
3              3                     Suzuki Alto VXL AGS 2021  8434139   
4              4                           Suzuki Alto L 2021  8317930   
...          ...                                          ...      ...   
4498         689                         Daihatsu Mira L 2021  8419350   
4499         690                   Honda City 1.3 i-VTEC 2019  8419342   
4500         691                        Honda City i-DSI 2004  8419320   
4501         692                   Honda City 1.3 i-VTEC 2016  8313103   
4502         693  Honda City Aspire Prosmatec 1.5 i-VTEC 2017  8322928   

     Engine Capacity   Category Body Consition  model Year      Milage  \
0             660 cc  Hatchback      Excellent        2020   23,000 km   
1             660 cc  Hatchback           Fair        2021   33,000 km   
2            1000 cc  Hatchback           Good        2011  244,672 km   
3             660 cc  Hatchback           Fair        2021   35,000 km   
4             660 cc  Hatchback      Excellent        2021    3,770 km   
...              ...        ...            ...         ...         ...   
4498          660 cc  Hatchback      Excellent        2021   59,000 km   
4499         1300 cc      Sedan      Excellent        2019  175,000 km   
4500         1300 cc      Sedan      Excellent        2004  100,000 km   
4501         1300 cc      Sedan           Good        2016   71,000 km   
4502         1500 cc      Sedan           Good        2017   32,000 km   

     Fuel Type Transmission          Color City Registered           Price  \
0       Petrol    Automatic          White   Un-Registered   PKR 31.5 lacs   
1       Petrol       Manual    Solid White          Punjab  PKR 22.35 lacs   
2       Petrol       Manual  Graphite Grey          Lahore     PKR 11 lacs   
3       Petrol    Automatic  Graphite Grey         Karachi  PKR 26.25 lacs   
4       Petrol    Automatic            Red   Un-Registered   PKR 34.8 lacs   
...        ...          ...            ...             ...             ...   
4498    Petrol    Automatic          White          Punjab  PKR 23.75 lacs   
4499    Petrol       Manual  Taffeta White          Lahore   PKR 33.5 lacs   
4500    Petrol       Manual          White         Karachi  PKR 14.25 lacs   
4501    Petrol       Manual          White          Lahore   PKR 32.5 lacs   
4502    Petrol    Automatic           Grey         Karachi   PKR 35.8 lacs   

                                                Ad_link       ad_Date  \
0     https://www.pakwheels.com/used-cars/suzuki-alt...  Feb 27, 2024   
1     https://www.pakwheels.com/used-cars/suzuki-alt...  Feb 27, 2024   
2     https://www.pakwheels.com/used-cars/suzuki-alt...  Feb 27, 2024   
3     https://www.pakwheels.com/used-cars/suzuki-alt...  Feb 27, 2024   
4     https://www.pakwheels.com/used-cars/suzuki-alt...  Feb 27, 2024   
...                                                 ...           ...   
4498  https://www.pakwheels.com/used-cars/daihatsu-m...  Feb 23, 2024   
4499  https://www.pakwheels.com/used-cars/honda-city...  Feb 23, 2024   
4500  https://www.pakwheels.com/used-cars/honda-city...  Feb 23, 2024   
4501  https://www.pakwheels.com/used-cars/honda-city...  Feb 23, 2024   
4502  https://www.pakwheels.com/used-cars/honda-city...  Feb 23, 2024   

      Unnamed: 0.1  
0              NaN  
1              NaN  
2              NaN  
3              NaN  
4              NaN  
...            ...  
4498         689.0  
4499         690.0  
4500         691.0  
4501         692.0  
4502         693.0  

[4503 rows x 16 columns]

In [15]:
df_con.to_csv("DATASETCON2.csv")

In [16]:
data = ['DATASETCON.csv','DATASETCON2.csv']
combined_data = pd.concat([pd.read_csv(f) for f in data], ignore_index= True)
combined_data

Unnamed: 0.1  Unnamed: 0                                      AD_Name  \
0               0.0           0         Changan Alsvin 1.5L DCT Lumiere 2022   
1               1.0           1                  Toyota Yaris Hatchback 2020   
2               2.0           2         Changan Alsvin 1.5L DCT Lumiere 2023   
3               3.0           3         Changan Alsvin 1.5L DCT Comfort 2022   
4               4.0           4         Changan Alsvin 1.5L DCT Lumiere 2021   
...             ...         ...                                          ...   
17762         689.0         689                         Daihatsu Mira L 2021   
17763         690.0         690                   Honda City 1.3 i-VTEC 2019   
17764         691.0         691                        Honda City i-DSI 2004   
17765         692.0         692                   Honda City 1.3 i-VTEC 2016   
17766         693.0         693  Honda City Aspire Prosmatec 1.5 i-VTEC 2017   

         AD_id Engine Capacity   Category Body Consition  model Year  \
0      8205716         1500 cc      Sedan      Excellent        2022   
1      8284829         1000 cc        NaN      Excellent        2020   
2      8422204         1500 cc      Sedan      Excellent        2023   
3      8367180         1500 cc      Sedan      Excellent        2022   
4      8307134         1500 cc      Sedan      Excellent        2021   
...        ...             ...        ...            ...         ...   
17762  8419350          660 cc  Hatchback      Excellent        2021   
17763  8419342         1300 cc      Sedan      Excellent        2019   
17764  8419320         1300 cc      Sedan      Excellent        2004   
17765  8313103         1300 cc      Sedan           Good        2016   
17766  8322928         1500 cc      Sedan           Good        2017   

           Milage Fuel Type Transmission          Color City Registered  \
0       46,000 km    Petrol    Automatic  Steller White          Punjab   
1      100,000 km    Petrol    Automatic         Silver   Un-Registered   
2       14,717 km    Petrol    Automatic   Lunar Silver       Islamabad   
3       40,737 km    Petrol    Automatic  Steller White       Islamabad   
4       59,155 km    Petrol    Automatic  Steller White         Karachi   
...           ...       ...          ...            ...             ...   
17762   59,000 km    Petrol    Automatic          White          Punjab   
17763  175,000 km    Petrol       Manual  Taffeta White          Lahore   
17764  100,000 km    Petrol       Manual          White         Karachi   
17765   71,000 km    Petrol       Manual          White          Lahore   
17766   32,000 km    Petrol    Automatic           Grey         Karachi   

                Price                                            Ad_link  \
0         PKR 39 lacs  https://www.pakwheels.com/used-cars/changan-al...   
1      PKR 45.75 lacs  https://www.pakwheels.com/used-cars/toyota-yar...   
2       PKR 42.5 lacs  https://www.pakwheels.com/used-cars/changan-al...   
3         PKR 31 lacs  https://www.pakwheels.com/used-cars/changan-al...   
4         PKR 35 lacs  https://www.pakwheels.com/used-cars/changan-al...   
...               ...                                                ...   
17762  PKR 23.75 lacs  https://www.pakwheels.com/used-cars/daihatsu-m...   
17763   PKR 33.5 lacs  https://www.pakwheels.com/used-cars/honda-city...   
17764  PKR 14.25 lacs  https://www.pakwheels.com/used-cars/honda-city...   
17765   PKR 32.5 lacs  https://www.pakwheels.com/used-cars/honda-city...   
17766   PKR 35.8 lacs  https://www.pakwheels.com/used-cars/honda-city...   

            ad_Date  Unnamed: 0.2  
0               NaN           NaN  
1               NaN           NaN  
2               NaN           NaN  
3               NaN           NaN  
4               NaN           NaN  
...             ...           ...  
17762  Feb 23, 2024        4498.0  
17763  Feb 23, 2024        4499.0  
17764  Feb 23, 2024        4500.0  
17765  

In [17]:
combined_data.to_csv("All_combined.csv")

In [18]:
pd.read_csv("All_combined.csv")

Unnamed: 0.3  Unnamed: 0.1  Unnamed: 0  \
0                 0           0.0           0   
1                 1           1.0           1   
2                 2           2.0           2   
3                 3           3.0           3   
4                 4           4.0           4   
...             ...           ...         ...   
17762         17762         689.0         689   
17763         17763         690.0         690   
17764         17764         691.0         691   
17765         17765         692.0         692   
17766         17766         693.0         693   

                                           AD_Name    AD_id Engine Capacity  \
0             Changan Alsvin 1.5L DCT Lumiere 2022  8205716         1500 cc   
1                      Toyota Yaris Hatchback 2020  8284829         1000 cc   
2             Changan Alsvin 1.5L DCT Lumiere 2023  8422204         1500 cc   
3             Changan Alsvin 1.5L DCT Comfort 2022  8367180         1500 cc   
4             Changan Alsvin 1.5L DCT Lumiere 2021  8307134         1500 cc   
...                                            ...      ...             ...   
17762                         Daihatsu Mira L 2021  8419350          660 cc   
17763                   Honda City 1.3 i-VTEC 2019  8419342         1300 cc   
17764                        Honda City i-DSI 2004  8419320         1300 cc   
17765                   Honda City 1.3 i-VTEC 2016  8313103         1300 cc   
17766  Honda City Aspire Prosmatec 1.5 i-VTEC 2017  8322928         1500 cc   

        Category Body Consition  model Year      Milage Fuel Type  \
0          Sedan      Excellent        2022   46,000 km    Petrol   
1            NaN      Excellent        2020  100,000 km    Petrol   
2          Sedan      Excellent        2023   14,717 km    Petrol   
3          Sedan      Excellent        2022   40,737 km    Petrol   
4          Sedan      Excellent        2021   59,155 km    Petrol   
...          ...            ...         ...         ...       ...   
17762  Hatchback      Excellent        2021   59,000 km    Petrol   
17763      Sedan      Excellent        2019  175,000 km    Petrol   
17764      Sedan      Excellent        2004  100,000 km    Petrol   
17765      Sedan           Good        2016   71,000 km    Petrol   
17766      Sedan           Good        2017   32,000 km    Petrol   

      Transmission          Color City Registered           Price  \
0        Automatic  Steller White          Punjab     PKR 39 lacs   
1        Automatic         Silver   Un-Registered  PKR 45.75 lacs   
2        Automatic   Lunar Silver       Islamabad   PKR 42.5 lacs   
3        Automatic  Steller White       Islamabad     PKR 31 lacs   
4        Automatic  Steller White         Karachi     PKR 35 lacs   
...            ...            ...             ...             ...   
17762    Automatic          White          Punjab  PKR 23.75 lacs   
17763       Manual  Taffeta White          Lahore   PKR 33.5 lacs   
17764       Manual          White         Karachi  PKR 14.25 lacs   
17765       Manual          White          Lahore   PKR 32.5 lacs   
17766    Automatic           Grey         Karachi   PKR 35.8 lacs   

                                                 Ad_link       ad_Date  \
0      https://www.pakwheels.com/used-cars/changan-al...           NaN   
1      https://www.pakwheels.com/used-cars/toyota-yar...           NaN   
2      https://www.pakwheels.com/used-cars/changan-al...           NaN   
3      https://www.pakwheels.com/used-cars/changan-al...           NaN   
4      https://www.pakwheels.com/used-cars/changan-al...           NaN   
...                                                  ...           ...   
17762  https://www.pakwheels.com/used-cars/daihatsu-m...  Feb 23, 2024   
17763  https://www.pakwheels.com/used-cars/honda-city...  Feb 23, 2024   
17764  https://www.pakwheels.com/used-cars/honda-city...  Feb 23, 2024   
17765  https://www.pakwheels.com/used-cars/honda-city...  Feb 23, 2024 

Loading the Dataset

In [2]:
dataset = pd.read_csv('./DataScrappingPart/FYP_DataSet.csv') 

### 

<h4>Visulizing and Preparing the Dataset

In [3]:
dataset.head()

Unnamed: 0 Car_Name Car_Brand Engine Capacity   Category  model Year  \
0           0    Swift    Suzuki         1200 cc  Hatchback        2022   
1           1    Swift    Suzuki         1300 cc  Hatchback        2018   
2           2    Swift    Suzuki         1200 cc  Hatchback        2023   
3           3    Swift    Suzuki         1300 cc  Hatchback        2017   
4           4    Swift    Suzuki         1300 cc  Hatchback        2021   

      Milage Fuel Type Transmission City Registered           Price  
0  19,700 km    Petrol    Automatic          Punjab  PKR 38.45 lacs  
1  82,000 km    Petrol       Manual          Lahore     PKR 27 lacs  
2   6,000 km    Petrol    Automatic       Islamabad     PKR 46 lacs  
3  81,000 km    Petrol    Automatic           Sindh   PKR 23.9 lacs  
4  74,542 km    Petrol       Manual          Punjab   PKR 26.9 lacs

In [4]:
dataset.tail()

Unnamed: 0 Car_Name Car_Brand Engine Capacity Category  model Year  \
8031        8031   Alsvin   Changan         1300 cc    Sedan        2021   
8032        8032   Alsvin   Changan         1500 cc    Sedan        2023   
8033        8033   Alsvin   Changan         1500 cc    Sedan        2022   
8034        8034   Alsvin   Changan         1500 cc    Sedan        2022   
8035        8035   Alsvin   Changan         1500 cc    Sedan        2021   

         Milage Fuel Type Transmission City Registered          Price  
8031  60,000 km    Petrol       Manual          Punjab    PKR 33 lacs  
8032   9,000 km    Petrol    Automatic          Lahore    PKR 43 lacs  
8033   6,500 km    Petrol    Automatic       Islamabad  PKR 41.5 lacs  
8034  18,675 km    Petrol    Automatic       Islamabad  PKR 40.5 lacs  
8035  60,000 km    Petrol    Automatic          Punjab    PKR 40 lacs

In [5]:
# Dropping the First Column named Unnamed
dataset.drop(dataset.columns[0],axis=1,inplace=True)

In [6]:
print("The null Values\n",dataset.isnull().sum())


The null Values
 Car_Name             0
Car_Brand            0
Engine Capacity      0
Category           655
model Year           0
Milage               0
Fuel Type            0
Transmission         0
City Registered      0
Price                0
dtype: int64


In [7]:
print("Data Info")
print(dataset.info())

Data Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8036 entries, 0 to 8035
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Car_Name         8036 non-null   object
 1   Car_Brand        8036 non-null   object
 2   Engine Capacity  8036 non-null   object
 3   Category         7381 non-null   object
 4   model Year       8036 non-null   int64 
 5   Milage           8036 non-null   object
 6   Fuel Type        8036 non-null   object
 7   Transmission     8036 non-null   object
 8   City Registered  8036 non-null   object
 9   Price            8036 non-null   object
dtypes: int64(1), object(9)
memory usage: 627.9+ KB
None


Finding the unique values from Engine Capacity Column

In [8]:
dataset['Engine Capacity'].unique()

array(['1200 cc', '1300 cc', '1242 cc', '1240 cc', '1800 cc', '1000 cc',
       '100 cc', '660 cc',
       '<bound method PageElement.get_text of <li>77.0 kWh</li>>',
       '796 cc', '1600 cc', '1500 cc', '1598 cc', '2200 cc', '2000 cc',
       '1798 cc', '1750 cc', '2700 cc', '15000 cc', '2500 cc', '2400 cc',
       '160 cc', '1497 cc', '700 cc', '800 cc', '1100 cc', '10000 cc',
       '4600 cc', '1198 cc', '4164 cc', '1400 cc', '3000 cc', '2800 cc',
       '659 cc', '998 cc', '996 cc', '1298 cc', '130 cc', '1299 cc',
       '658 cc',
       '<bound method PageElement.get_text of <li>10.0 kWh</li>>',
       '3400 cc', '6600 cc', '900 cc', '880 cc', '4200 cc'], dtype=object)

From above we can see that there are some unwanted data , so we have to clean it up


In [9]:
# Replacing CC with ''
dataset['Engine Capacity'] = dataset['Engine Capacity'].str.replace(' cc', '')


In [10]:
print(dataset.loc[dataset['Engine Capacity'] == '1200'])

     Car_Name Car_Brand Engine Capacity       Category  model Year     Milage  \
0       Swift    Suzuki            1200      Hatchback        2022  19,700 km   
2       Swift    Suzuki            1200      Hatchback        2023   6,000 km   
9       Swift    Suzuki            1200      Hatchback        2023  13,056 km   
10      Swift    Suzuki            1200      Hatchback        2022     400 km   
16      Swift    Suzuki            1200      Hatchback        2022  18,000 km   
...       ...       ...             ...            ...         ...        ...   
5247     City     Honda            1200  Compact sedan        2022  19,000 km   
5253     City     Honda            1200  Compact sedan        2021   9,000 km   
5256     City     Honda            1200            NaN        2022   9,500 km   
5265     City     Honda            1200  Compact sedan        2022  21,000 km   
5275     City     Honda            1200  Compact sedan        2023  16,600 km   

     Fuel Type Transmission

Replacing the 1750 or 1798 15000 1198 4164 and other like this into better form<br>
4164 is lancruiser<br>
4600 is landcruiser<br>
6600 is bolan<br>
3400 is pajero
<br>4200 is bolan too
<br>700 is mehran<br>
160 is sportage 

<br>
4164 to 4600<br>
6600 to 660<br>
4200 to 660<br>
700 to 800<br>
160 to 2000<br>
900 to 100<br>
1100 to 1000<br>
all 900 to 1000<br>
1400 to 1500<br>
<br><bound method PageElement.get_text of <li>10.0 kWh</li>> to 1800
100 to 1000 and 660 and 1300 plz check it before doing

now replacing



In [11]:
dataset.loc[dataset['Car_Name'] == 'Swift', 'Engine Capacity'] = dataset.loc[dataset['Car_Name'] == 'Swift', 'Engine Capacity'].replace('100', '1300')
dataset.loc[dataset['Car_Name'] == 'Bolan', 'Engine Capacity'] = dataset.loc[dataset['Car_Name'] == 'Bolan', 'Engine Capacity'].replace('100', '800')



In [12]:
dataset["Engine Capacity"] = dataset['Engine Capacity'].replace({
    '160': '2000',
    '4164': '4600',
    '4200': '660',
    '700': '800',
    '900': '1000',
    '1100': '1000',
    '700': '800',
    '1798': '1800',
    '1750': '1800',
    '998': '1000',
    '996': '1000',
    '1750': '1800',
    '1400': '1500',
    '130': '1300',
    '1200':'1300',
    '1242':'1300',
    '1240':'1300',
    '100':'1000',
    '796':'800',
    '659':'660',
    '658' :'660',
    '1198':'1200',
    '1298':'1300',
    '880':'800',
    '1299':'1300',
    '1497':'1500',
    '<bound method PageElement.get_text of <li>77.0 kWh</li>>':'1800 ',
    '1200':'1300',
    '1598':'1600',
    '15000':'1500',
    '<bound method PageElement.get_text of <li>10.0 kWh</li>>':'1800',
    '2200':'2000',
    '100':'1000',
    '10000':'1000',
    '1800 ':'1800',
    '1200':'1300'
    
    })

In [13]:
dataset['Engine Capacity'].unique()

array(['1300', '1800', '1000', '660', '1800 ', '800', '1600', '1500',
       '2000', '2700', '2500', '2400', '4600', '1200', '3000', '2800',
       '3400', '6600'], dtype=object)

Now converting the whole column to int

In [14]:
dataset['Engine Capacity'] = dataset["Engine Capacity"].astype('int64')

In [15]:
dataset.dtypes

Car_Name           object
Car_Brand          object
Engine Capacity     int64
Category           object
model Year          int64
Milage             object
Fuel Type          object
Transmission       object
City Registered    object
Price              object
dtype: object

<h2>Price column is done</h2>
Now its time for price

In [16]:
dataset['Price']

0       PKR 38.45 lacs
1          PKR 27 lacs
2          PKR 46 lacs
3        PKR 23.9 lacs
4        PKR 26.9 lacs
             ...      
8031       PKR 33 lacs
8032       PKR 43 lacs
8033     PKR 41.5 lacs
8034     PKR 40.5 lacs
8035       PKR 40 lacs
Name: Price, Length: 8036, dtype: object

In [17]:
# replacing the un-wanted words , and converting the crore price in lacs
dataset = dataset[~dataset['Price'].str.contains("Call for price")] 
dataset["Price"] = dataset['Price'].str.replace('PKR','')
dataset["Price"] = dataset['Price'].str.replace("crore",'100')
dataset["Price"] = dataset['Price'].str.replace("lacs",'')
dataset.loc[:, 'Price'] = dataset['Price'].apply(lambda x: float(x.replace(' 100', '')) * 100 if '100' in str(x) else x)


In [18]:
dataset["Price"] = dataset["Price"].astype('float')

In [19]:
dataset.dtypes

Car_Name            object
Car_Brand           object
Engine Capacity      int64
Category            object
model Year           int64
Milage              object
Fuel Type           object
Transmission        object
City Registered     object
Price              float64
dtype: object

Price is done now for Millage

In [22]:
dataset["Milage"] = dataset["Milage"].str.replace(" km",'')
dataset["Milage"] = dataset["Milage"].str.replace(",",'')

dataset["Milage"] = dataset['Milage'].astype('int64')

In [24]:
dataset['Milage'].dtypes

dtype('int64')

<h2>Now categroy

In [37]:
print(dataset['Category'].isna().sum())

654


In [34]:
# Assuming your DataFrame is named 'data'
# Print rows where "Category" column is empty

print(dataset[dataset['Category'].isnull() | (dataset['Category'] == '')])

     Car_Name Car_Brand  Engine Capacity Category  model Year  Milage  \
12      Swift    Suzuki             1300      NaN        2020   48208   
46      Swift    Suzuki             1300      NaN        2022   17000   
90      Swift    Suzuki             1300      NaN        2020   77000   
111     Yaris    Toyota             1000      NaN        2020   92000   
123     Swift    Suzuki             1800      NaN        1989  150000   
...       ...       ...              ...      ...         ...     ...   
7670   Alsvin   Changan             1500      NaN        2020   55000   
7683    Yaris    Toyota             1000      NaN        2020   92000   
7761     Boon  Daihatsu             1000      NaN        2020   13500   
7780   Alsvin   Changan             1000      NaN        2021   75000   
7809   Alsvin   Changan             1000      NaN        2021   75000   

     Fuel Type Transmission City Registered  Price  
12      Petrol    Automatic          Punjab  32.00  
46      Petrol   

Replacing NAN with respective category manually

In [64]:
dataset.loc[(dataset['Car_Name'] == 'Swift') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'
dataset.loc[(dataset['Car_Name'] == 'Yaris') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Sedan'
dataset.loc[(dataset['Car_Name'] == 'Khyber') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'
dataset.loc[(dataset['Car_Name'] == 'Margalla') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Sedan'
dataset.loc[(dataset['Car_Name'] == 'Corolla') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Sedan'
dataset.loc[(dataset['Car_Name'] == 'Civic') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Sedan'
dataset.loc[(dataset['Car_Name'] == 'Alsvin') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Sedan'
dataset.loc[(dataset['Car_Name'] == 'Sportage') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'SUV'
dataset.loc[(dataset['Car_Name'] == 'Bolan') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Van'
dataset.loc[(dataset['Car_Name'] == 'Elantra') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Sedan'
dataset.loc[(dataset['Car_Name'] == 'Charade') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'
dataset.loc[(dataset['Car_Name'] == 'Boon') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'

dataset.loc[(dataset['Car_Name'] == 'Mehran') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'
dataset.loc[(dataset['Car_Name'] == 'Boon') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'
dataset.loc[(dataset['Car_Name'] == 'Rocky') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Crossover'
dataset.loc[(dataset['Car_Name'] == 'Prius') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Sedan'
dataset.loc[(dataset['Car_Name'] == 'Wagon') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'

dataset.loc[(dataset['Car_Name'] == 'FX') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'
dataset.loc[(dataset['Car_Name'] == 'N') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'
dataset.loc[(dataset['Car_Name'] == 'Polo') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'

dataset.loc[(dataset['Car_Name'] == 'Alpha') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'
dataset.loc[(dataset['Car_Name'] == 'Cultus') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'
dataset.loc[(dataset['Car_Name'] == 'Passo') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'
dataset.loc[(dataset['Car_Name'] == 'Carry') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Van'

dataset.loc[(dataset['Car_Name'] == 'City') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Sedan'
dataset.loc[(dataset['Car_Name'] == 'Sunny') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Sedan'

dataset.loc[(dataset['Car_Name'] == 'Liana') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Sedan'
dataset.loc[(dataset['Car_Name'] == 'QQ') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'

dataset.loc[(dataset['Car_Name'] == 'Vitz') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'

dataset.loc[(dataset['Car_Name'] == 'Move') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'

dataset.loc[(dataset['Car_Name'] == 'Vezel') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Crossover'

dataset.loc[(dataset['Car_Name'] == 'Rover') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Crossover'
dataset.loc[(dataset['Car_Name'] == 'Cuore') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'
dataset.loc[(dataset['Car_Name'] == 'Dayz') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'Hatchback'

dataset.loc[(dataset['Car_Name'] == 'Prado') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'SUV'
dataset.loc[(dataset['Car_Name'] == 'Pajero') & (dataset['Category'].isnull() | (dataset['Category'] == '')), 'Category'] = 'SUV'

print(dataset[dataset['Category'].isnull() | (dataset['Category'] == '')])
print('cate', dataset['Category'].isna().sum())


     Car_Name  Car_Brand  Engine Capacity Category  model Year  Milage  \
2678  Electra      Buick             2000      NaN        2022   31400   
4730     Surf     Toyota             2700      NaN        1998   75000   
5067     Esse   Daihatsu              660      NaN        2009  160000   
5085     Surf     Toyota             2700      NaN        1998   75000   
5180   Stavic  SsangYong             2700      NaN        2007  120000   
5386    Every     Suzuki              660      NaN        2017  135200   
5771        X     Nissan             2000      NaN        2008  290000   
5772        X     Nissan             2000      NaN        2008  290000   
6155      Kei     Suzuki              660      NaN        2007  165000   
7056    Auris     Toyota             1800      NaN        2016  104000   

     Fuel Type Transmission City Registered  Price  
2678    Petrol    Automatic       Islamabad   62.5  
4730    Petrol    Automatic          Lahore   38.0  
5067    Petrol       Manua

In [71]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7990 entries, 0 to 8035
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Car_Name         7990 non-null   object 
 1   Car_Brand        7990 non-null   object 
 2   Engine Capacity  7990 non-null   int64  
 3   Category         7980 non-null   object 
 4   model Year       7990 non-null   int64  
 5   Milage           7990 non-null   int64  
 6   Fuel Type        7990 non-null   object 
 7   Transmission     7990 non-null   object 
 8   City Registered  7990 non-null   object 
 9   Price            7990 non-null   float64
dtypes: float64(1), int64(3), object(6)
memory usage: 944.7+ KB


Now Brands

In [76]:
print(dataset["Car_Brand"].unique())

['Suzuki' 'Honda' 'Nissan' 'Toyota' 'Subaru' 'MG' 'Changan' 'Daihatsu'
 'KIA' 'Haval' 'Hyundai' 'Peugeot' 'Chery' 'Volkswagen' 'Chevrolet'
 'Mazda' 'BMW' 'Mitsubishi' 'Mercedes' 'Land' 'Proton' 'United']


In [75]:
# deleting the row where brank name is SsangYong and Buick and Chery

dataset = dataset[~dataset['Car_Brand'].str.contains("SsangYong")]

In [77]:
print(dataset['Car_Name'].unique())

['Swift' 'Civic' 'Khyber' 'Note' 'Wagon' 'Yaris' 'Vitz' 'Cultus' 'R2' '4'
 'Mehran' 'Alsvin' 'Margalla' 'Corolla' 'Grace' 'Alto' 'Premio' 'Passo'
 'Charade' 'HS' 'City' 'Hiace' 'Sportage' 'C-HR' 'Jolion' 'Oshan'
 'Elantra' 'Vezel' 'Sienta' 'Surf' '2008' 'BR-V' 'QQ' 'Cuore' 'Baleno'
 'Beetle' 'Spark' 'Flair' 'FX' 'Sunny' 'Picanto' 'N' 'Polo' 'Move'
 'Santro' 'Dayz' '3' 'Ravi' 'EK' 'Land' 'Esquire' 'Prius' 'Hustler' 'Mira'
 'Life' 'Pleo' 'Aqua' 'MR' 'Allion' 'Liana' 'Benz' 'Belta' 'Mark' 'ZS'
 'Sonata' 'Spacia' 'Esse' 'Prado' 'Rover' 'Mirage' 'Every' 'AD' 'Raize'
 'Platz' 'X' 'Saga' 'Boon' 'Kei' 'Roomy' 'Alpha' 'Pixis' 'Pajero' 'Auris'
 'Bolan' 'Hijet' 'Rocky' 'Carry' 'Ciaz']


to delete 
<br>Pleo<br>
R2
Polo
Kei
MR
Allion
QQ
Pixis
Roomy
Beetle
Esquire
Esse
Boon
<br>
To Re-name
<br>
3 is BMW 3 series, 2008 is peugeot, Carry is Bolan , 4 is MG , Wagon is Wagon R, X is Nissan, Mark is MarkX

In [119]:
print(dataset.loc[dataset['Car_Name'] == ''])

     Car_Name Car_Brand  Engine Capacity Category  model Year  Milage  \
5022   Mark X    Toyota             3000    Sedan        2005  118253   

     Fuel Type Transmission City Registered  Price  
5022    Petrol    Automatic           Sindh   42.0  


In [112]:
unwanted_car_names = ['Pleo', 'R2', 'Polo', 'Kei', 'MR', 'Allion', 'QQ', 'Pixis', 'Roomy', 'Beetle', 'Esquire', 'Esse', 'Boon']

# Filter out rows where Car_Name is in the list of unwanted car names
dataset = dataset[~dataset['Car_Name'].isin(unwanted_car_names)]


In [117]:
# now renaming some names
#3 is BMW 3 series, 2008 is peugeot, Carry is Bolan , 4 is MG , Wagon is Wagon R, X is Nissan, Mark is MarkX
dataset['Car_Name'] = dataset['Car_Name'].replace({'3':"BMW 3 Series",
                                                       '2008':'Peugeot 2008',
                                                       'Carry':'Bolan',
                                                       '4':'MG 4',
                                                       'Wagon':'Wagon R',
                                                       'X':'Nissan X',
                                                       'Mark':"Mark X"})

C:\Users\M_ros\AppData\Local\Temp\ipykernel_24232\3061313971.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Car_Name'] = dataset['Car_Name'].replace({'3':"BMW 3 Series",


In [118]:
dataset

Car_Name Car_Brand  Engine Capacity   Category  model Year  Milage  \
0       Swift    Suzuki             1300  Hatchback        2022   19700   
1       Swift    Suzuki             1300  Hatchback        2018   82000   
2       Swift    Suzuki             1300  Hatchback        2023    6000   
3       Swift    Suzuki             1300  Hatchback        2017   81000   
4       Swift    Suzuki             1300  Hatchback        2021   74542   
...       ...       ...              ...        ...         ...     ...   
8031   Alsvin   Changan             1300      Sedan        2021   60000   
8032   Alsvin   Changan             1500      Sedan        2023    9000   
8033   Alsvin   Changan             1500      Sedan        2022    6500   
8034   Alsvin   Changan             1500      Sedan        2022   18675   
8035   Alsvin   Changan             1500      Sedan        2021   60000   

     Fuel Type Transmission City Registered  Price  
0       Petrol    Automatic          Punjab  38.45  
1       Petrol       Manual          Lahore  27.00  
2       Petrol    Automatic       Islamabad  46.00  
3       Petrol    Automatic           Sindh  23.90  
4       Petrol       Manual          Punjab  26.90  
...        ...          ...             ...    ...  
8031    Petrol       Manual          Punjab  33.00  
8032    Petrol    Automatic          Lahore  43.00  
8033    Petrol    Automatic       Islamabad  41.50  
8034    Petrol    Automatic       Islamabad  40.50  
8035    Petrol    Automatic          Punjab  40.00  

[7967 rows x 10 columns]

<h3>Now saving the dataset into csv with name 'Clean1.csv'


In [120]:
dataset.to_csv('Clean1.csv')

<h1>Now from file FYP dataset2 and dataset3

In [150]:
dataset2 = pd.read_csv('./DataScrappingPart/FYP DataSet2.csv')


In [151]:
dataset2

Car_Name Car_Brand Engine Capacity Category  model Year      Milage  \
0    Fortuner    Toyota         2800 cc      SUV        2021   39,235 km   
1    Fortuner    Toyota         2700 cc      SUV        2015  140,000 km   
2    Fortuner    Toyota         2800 cc      SUV        2022   19,800 km   
3    Fortuner    Toyota         2700 cc      SUV        2017   67,987 km   
4    Fortuner    Toyota         2800 cc      SUV        2021   13,500 km   
..        ...       ...             ...      ...         ...         ...   
594    Tucson   Hyundai         2000 cc      SUV        2021   40,000 km   
595    Tucson   Hyundai         2000 cc      SUV        2021   40,000 km   
596    Tucson   Hyundai         2000 cc      SUV        2021   40,000 km   
597    Tucson   Hyundai         2000 cc      SUV        2021   40,000 km   
598    Tucson   Hyundai         2000 cc      SUV        2021   40,000 km   

    Fuel Type Transmission City Registered           Price  
0      Diesel    Automatic       Islamabad  PKR 1.64 crore  
1      Petrol    Automatic       Islamabad   PKR 78.5 lacs  
2      Diesel    Automatic          Lahore   PKR 1.7 crore  
3      Petrol    Automatic         Karachi  PKR 1.03 crore  
4      Diesel    Automatic          Punjab  PKR 1.68 crore  
..        ...          ...             ...             ...  
594    Petrol    Automatic         Karachi     PKR 82 lacs  
595    Petrol    Automatic         Karachi     PKR 82 lacs  
596    Petrol    Automatic         Karachi     PKR 82 lacs  
597    Petrol    Automatic         Karachi     PKR 82 lacs  
598    Petrol    Automatic         Karachi     PKR 82 lacs  

[599 rows x 10 columns]

In [152]:
# replacing the un-wanted words , and converting the crore price in lacs
dataset2 = dataset2[~dataset2['Price'].str.contains("Call for price")] 
dataset2["Price"] = dataset2['Price'].str.replace('PKR','')
dataset2["Price"] = dataset2['Price'].str.replace("crore",'100')
dataset2["Price"] = dataset2['Price'].str.replace("lacs",'')
dataset2.loc[:, 'Price'] = dataset2['Price'].apply(lambda x: float(x.replace(' 100', '')) * 100 if '100' in str(x) else x)


C:\Users\M_ros\AppData\Local\Temp\ipykernel_24232\3179653247.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2["Price"] = dataset2['Price'].str.replace('PKR','')
C:\Users\M_ros\AppData\Local\Temp\ipykernel_24232\3179653247.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2["Price"] = dataset2['Price'].str.replace("crore",'100')
C:\Users\M_ros\AppData\Local\Temp\ipykernel_24232\3179653247.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Tr

In [153]:
dataset2['Price'] = dataset2['Price'].astype('float')


C:\Users\M_ros\AppData\Local\Temp\ipykernel_24232\4161625442.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2['Price'] = dataset2['Price'].astype('float')


In [155]:
dataset2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 561 entries, 0 to 598
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Car_Name         561 non-null    object 
 1   Car_Brand        561 non-null    object 
 2   Engine Capacity  561 non-null    object 
 3   Category         553 non-null    object 
 4   model Year       561 non-null    int64  
 5   Milage           561 non-null    object 
 6   Fuel Type        561 non-null    object 
 7   Transmission     561 non-null    object 
 8   City Registered  561 non-null    object 
 9   Price            561 non-null    float64
dtypes: float64(1), int64(1), object(8)
memory usage: 48.2+ KB


In [159]:
dataset2['Milage'] = dataset2['Milage'].str.replace('km','')
dataset2['Milage'] = dataset2['Milage'].str.replace(',','')
dataset2["Milage"] = dataset2["Milage"].astype('int64')


C:\Users\M_ros\AppData\Local\Temp\ipykernel_24232\802427848.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2['Milage'] = dataset2['Milage'].str.replace('km','')
C:\Users\M_ros\AppData\Local\Temp\ipykernel_24232\802427848.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2['Milage'] = dataset2['Milage'].str.replace(',','')
C:\Users\M_ros\AppData\Local\Temp\ipykernel_24232\802427848.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using

In [163]:
dataset2.loc[(dataset2['Car_Name'] == 'Fortuner') & (dataset2['Category'].isnull() | (dataset2['Category'] == '')), 'Category'] = 'SUV'
dataset2.loc[(dataset2['Car_Name'] == 'Benz') & (dataset2['Category'].isnull() | (dataset2['Category'] == '')), 'Category'] = 'Sedan'
dataset2.loc[(dataset2['Car_Name'] == 'Prius') & (dataset2['Category'].isnull() | (dataset2['Category'] == '')), 'Category'] = 'Sedan'


Merging the first and 2nd dataset


In [166]:
merge_dataset = pd.concat([dataset, dataset2], ignore_index=True)
merge_dataset.to_csv("Complete Clean Dataset.csv")